import React from 'react';

import './App.css';
import Bracket from './components/Bracket.js';

const obj = {
    "album": {
      "album_group": "album",
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
          },
          "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
          "id": "0k17h0D3J5VfsdmQ1iZtE9",
          "name": "Pink Floyd",
          "type": "artist",
          "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
        }
      ],
      "available_markets": [
        "AE",
        "AG",
        "AO",
        "AR",
        "AU",
        "BB",
        "BD",
        "BF",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "DJ",
        "DM",
        "DO",
        "EC",
        "EG",
        "ET",
        "FJ",
        "FM",
        "GA",
        "GD",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HT",
        "ID",
        "IL",
        "IN",
        "IQ",
        "JM",
        "JO",
        "JP",
        "KE",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "LA",
        "LB",
        "LC",
        "LK",
        "LR",
        "LS",
        "LY",
        "MG",
        "MH",
        "ML",
        "MO",
        "MR",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PS",
        "PW",
        "PY",
        "QA",
        "RW",
        "SA",
        "SB",
        "SC",
        "SG",
        "SL",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UG",
        "US",
        "UY",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "ZA",
        "ZM",
        "ZW"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/4LH4d3cOWNNsVw41Gqt2kv"
      },
      "href": "https://api.spotify.com/v1/albums/4LH4d3cOWNNsVw41Gqt2kv",
      "id": "4LH4d3cOWNNsVw41Gqt2kv",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/ab67616d0000b273ea7caaff71dea1051d49b2fe",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/ab67616d00001e02ea7caaff71dea1051d49b2fe",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/ab67616d00004851ea7caaff71dea1051d49b2fe",
          "width": 64
        }
      ],
      "name": "The Dark Side of the Moon",
      "release_date": "1973-03-01",
      "release_date_precision": "day",
      "total_tracks": 10,
      "type": "album",
      "uri": "spotify:album:4LH4d3cOWNNsVw41Gqt2kv"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
        },
        "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
        "id": "0k17h0D3J5VfsdmQ1iZtE9",
        "name": "Pink Floyd",
        "type": "artist",
        "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
      }
    ],
    "available_markets": [
      "AR",
      "AU",
      "BO",
      "BR",
      "CA",
      "CL",
      "CO",
      "CR",
      "DO",
      "EC",
      "SV",
      "GT",
      "HN",
      "HK",
      "MY",
      "MX",
      "NZ",
      "NI",
      "PA",
      "PY",
      "PE",
      "PH",
      "SG",
      "TW",
      "UY",
      "US",
      "ID",
      "JP",
      "TH",
      "VN",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "LA",
      "MO",
      "MR",
      "NP",
      "RW",
      "TG",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "VE",
      "ET"
    ],
    "disc_number": 1,
    "duration_ms": 283872,
    "explicit": false,
    "external_ids": {
      "isrc": "GBN9Y1100080"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/2TjdnqlpwOjhijHCwHCP2d"
    },
    "href": "https://api.spotify.com/v1/tracks/2TjdnqlpwOjhijHCwHCP2d",
    "id": "2TjdnqlpwOjhijHCwHCP2d",
    "is_local": false,
    "name": "The Great Gig in the Sky",
    "popularity": 77,
    "preview_url": "https://p.scdn.co/mp3-preview/a12c96145fa9ce6b6cf35b36f2655d582c58fd6f?cid=cfe923b2d660439caf2b557b21f31221",
    "track_number": 5,
    "type": "track",
    "uri": "spotify:track:2TjdnqlpwOjhijHCwHCP2d"
  };

const obj2 = {
    "album": {
      "album_group": "album",
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x"
          },
          "href": "https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x",
          "id": "5K4W6rqBFWDnAN6FQUkS6x",
          "name": "Kanye West",
          "type": "artist",
          "uri": "spotify:artist:5K4W6rqBFWDnAN6FQUkS6x"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IL",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/5ll74bqtkcXlKE7wwkMq4g"
      },
      "href": "https://api.spotify.com/v1/albums/5ll74bqtkcXlKE7wwkMq4g",
      "id": "5ll74bqtkcXlKE7wwkMq4g",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/ab67616d0000b273428d2255141c2119409a31b2",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/ab67616d00001e02428d2255141c2119409a31b2",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/ab67616d00004851428d2255141c2119409a31b2",
          "width": 64
        }
      ],
      "name": "Late Registration",
      "release_date": "2005-08-30",
      "release_date_precision": "day",
      "total_tracks": 21,
      "type": "album",
      "uri": "spotify:album:5ll74bqtkcXlKE7wwkMq4g"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x"
        },
        "href": "https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x",
        "id": "5K4W6rqBFWDnAN6FQUkS6x",
        "name": "Kanye West",
        "type": "artist",
        "uri": "spotify:artist:5K4W6rqBFWDnAN6FQUkS6x"
      },
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/20qISvAhX20dpIbOOzGK3q"
        },
        "href": "https://api.spotify.com/v1/artists/20qISvAhX20dpIbOOzGK3q",
        "id": "20qISvAhX20dpIbOOzGK3q",
        "name": "Nas",
        "type": "artist",
        "uri": "spotify:artist:20qISvAhX20dpIbOOzGK3q"
      },
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/69m0yjx8ruKebsRvbNuEDz"
        },
        "href": "https://api.spotify.com/v1/artists/69m0yjx8ruKebsRvbNuEDz",
        "id": "69m0yjx8ruKebsRvbNuEDz",
        "name": "Really Doe",
        "type": "artist",
        "uri": "spotify:artist:69m0yjx8ruKebsRvbNuEDz"
      }
    ],
    "available_markets": [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    "disc_number": 1,
    "duration_ms": 448000,
    "explicit": true,
    "external_ids": {
      "isrc": "USUM70502548"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/46fk9wjYcPm0sgym2b7EEE"
    },
    "href": "https://api.spotify.com/v1/tracks/46fk9wjYcPm0sgym2b7EEE",
    "id": "46fk9wjYcPm0sgym2b7EEE",
    "is_local": false,
    "name": "We Major",
    "popularity": 62,
    "preview_url": "https://p.scdn.co/mp3-preview/39230520170e190b84bd6761f02d4504dbb9cfc8?cid=cfe923b2d660439caf2b557b21f31221",
    "track_number": 14,
    "type": "track",
    "uri": "spotify:track:46fk9wjYcPm0sgym2b7EEE"
  };

function App() {
    return (
        <>
            <Bracket players={[obj,obj2]}/>
        </>
    );
}

export default App;
