import './App.css';

const obj = {
    "album": {
      "album_group": "album",
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
          },
          "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
          "id": "0k17h0D3J5VfsdmQ1iZtE9",
          "name": "Pink Floyd",
          "type": "artist",
          "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
        }
      ],
      "available_markets": [
        "AE",
        "AG",
        "AO",
        "AR",
        "AU",
        "BB",
        "BD",
        "BF",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "DJ",
        "DM",
        "DO",
        "EC",
        "EG",
        "ET",
        "FJ",
        "FM",
        "GA",
        "GD",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HT",
        "ID",
        "IL",
        "IN",
        "IQ",
        "JM",
        "JO",
        "JP",
        "KE",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "LA",
        "LB",
        "LC",
        "LK",
        "LR",
        "LS",
        "LY",
        "MG",
        "MH",
        "ML",
        "MO",
        "MR",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PS",
        "PW",
        "PY",
        "QA",
        "RW",
        "SA",
        "SB",
        "SC",
        "SG",
        "SL",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UG",
        "US",
        "UY",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "ZA",
        "ZM",
        "ZW"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/4LH4d3cOWNNsVw41Gqt2kv"
      },
      "href": "https://api.spotify.com/v1/albums/4LH4d3cOWNNsVw41Gqt2kv",
      "id": "4LH4d3cOWNNsVw41Gqt2kv",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/ab67616d0000b273ea7caaff71dea1051d49b2fe",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/ab67616d00001e02ea7caaff71dea1051d49b2fe",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/ab67616d00004851ea7caaff71dea1051d49b2fe",
          "width": 64
        }
      ],
      "name": "The Dark Side of the Moon",
      "release_date": "1973-03-01",
      "release_date_precision": "day",
      "total_tracks": 10,
      "type": "album",
      "uri": "spotify:album:4LH4d3cOWNNsVw41Gqt2kv"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
        },
        "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
        "id": "0k17h0D3J5VfsdmQ1iZtE9",
        "name": "Pink Floyd",
        "type": "artist",
        "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
      }
    ],
    "available_markets": [
      "AR",
      "AU",
      "BO",
      "BR",
      "CA",
      "CL",
      "CO",
      "CR",
      "DO",
      "EC",
      "SV",
      "GT",
      "HN",
      "HK",
      "MY",
      "MX",
      "NZ",
      "NI",
      "PA",
      "PY",
      "PE",
      "PH",
      "SG",
      "TW",
      "UY",
      "US",
      "ID",
      "JP",
      "TH",
      "VN",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "LA",
      "MO",
      "MR",
      "NP",
      "RW",
      "TG",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "VE",
      "ET"
    ],
    "disc_number": 1,
    "duration_ms": 283872,
    "explicit": false,
    "external_ids": {
      "isrc": "GBN9Y1100080"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/2TjdnqlpwOjhijHCwHCP2d"
    },
    "href": "https://api.spotify.com/v1/tracks/2TjdnqlpwOjhijHCwHCP2d",
    "id": "2TjdnqlpwOjhijHCwHCP2d",
    "is_local": false,
    "name": "The Great Gig in the Sky",
    "popularity": 77,
    "preview_url": "https://p.scdn.co/mp3-preview/a12c96145fa9ce6b6cf35b36f2655d582c58fd6f?cid=cfe923b2d660439caf2b557b21f31221",
    "track_number": 5,
    "type": "track",
    "uri": "spotify:track:2TjdnqlpwOjhijHCwHCP2d"
  };

function App() {
    return (
        <></>
    );
}

export default App;
