import React from 'react';

import './App.css';
import Bracket from './components/Bracket.js';

const obj = {
    "album": {
      "album_group": "album",
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
          },
          "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
          "id": "0k17h0D3J5VfsdmQ1iZtE9",
          "name": "Pink Floyd",
          "type": "artist",
          "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
        }
      ],
      "available_markets": [
        "AE",
        "AG",
        "AO",
        "AR",
        "AU",
        "BB",
        "BD",
        "BF",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "DJ",
        "DM",
        "DO",
        "EC",
        "EG",
        "ET",
        "FJ",
        "FM",
        "GA",
        "GD",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HT",
        "ID",
        "IL",
        "IN",
        "IQ",
        "JM",
        "JO",
        "JP",
        "KE",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "LA",
        "LB",
        "LC",
        "LK",
        "LR",
        "LS",
        "LY",
        "MG",
        "MH",
        "ML",
        "MO",
        "MR",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PS",
        "PW",
        "PY",
        "QA",
        "RW",
        "SA",
        "SB",
        "SC",
        "SG",
        "SL",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UG",
        "US",
        "UY",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "ZA",
        "ZM",
        "ZW"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/4LH4d3cOWNNsVw41Gqt2kv"
      },
      "href": "https://api.spotify.com/v1/albums/4LH4d3cOWNNsVw41Gqt2kv",
      "id": "4LH4d3cOWNNsVw41Gqt2kv",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/ab67616d0000b273ea7caaff71dea1051d49b2fe",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/ab67616d00001e02ea7caaff71dea1051d49b2fe",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/ab67616d00004851ea7caaff71dea1051d49b2fe",
          "width": 64
        }
      ],
      "name": "The Dark Side of the Moon",
      "release_date": "1973-03-01",
      "release_date_precision": "day",
      "total_tracks": 10,
      "type": "album",
      "uri": "spotify:album:4LH4d3cOWNNsVw41Gqt2kv"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
        },
        "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
        "id": "0k17h0D3J5VfsdmQ1iZtE9",
        "name": "Pink Floyd",
        "type": "artist",
        "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
      }
    ],
    "available_markets": [
      "AR",
      "AU",
      "BO",
      "BR",
      "CA",
      "CL",
      "CO",
      "CR",
      "DO",
      "EC",
      "SV",
      "GT",
      "HN",
      "HK",
      "MY",
      "MX",
      "NZ",
      "NI",
      "PA",
      "PY",
      "PE",
      "PH",
      "SG",
      "TW",
      "UY",
      "US",
      "ID",
      "JP",
      "TH",
      "VN",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "LA",
      "MO",
      "MR",
      "NP",
      "RW",
      "TG",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "VE",
      "ET"
    ],
    "disc_number": 1,
    "duration_ms": 283872,
    "explicit": false,
    "external_ids": {
      "isrc": "GBN9Y1100080"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/2TjdnqlpwOjhijHCwHCP2d"
    },
    "href": "https://api.spotify.com/v1/tracks/2TjdnqlpwOjhijHCwHCP2d",
    "id": "2TjdnqlpwOjhijHCwHCP2d",
    "is_local": false,
    "name": "The Great Gig in the Sky",
    "popularity": 77,
    "preview_url": "https://p.scdn.co/mp3-preview/a12c96145fa9ce6b6cf35b36f2655d582c58fd6f?cid=cfe923b2d660439caf2b557b21f31221",
    "track_number": 5,
    "type": "track",
    "uri": "spotify:track:2TjdnqlpwOjhijHCwHCP2d"
  };

const obj2 = {
    "album": {
      "album_group": "album",
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x"
          },
          "href": "https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x",
          "id": "5K4W6rqBFWDnAN6FQUkS6x",
          "name": "Kanye West",
          "type": "artist",
          "uri": "spotify:artist:5K4W6rqBFWDnAN6FQUkS6x"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IL",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/5ll74bqtkcXlKE7wwkMq4g"
      },
      "href": "https://api.spotify.com/v1/albums/5ll74bqtkcXlKE7wwkMq4g",
      "id": "5ll74bqtkcXlKE7wwkMq4g",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/ab67616d0000b273428d2255141c2119409a31b2",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/ab67616d00001e02428d2255141c2119409a31b2",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/ab67616d00004851428d2255141c2119409a31b2",
          "width": 64
        }
      ],
      "name": "Late Registration",
      "release_date": "2005-08-30",
      "release_date_precision": "day",
      "total_tracks": 21,
      "type": "album",
      "uri": "spotify:album:5ll74bqtkcXlKE7wwkMq4g"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x"
        },
        "href": "https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x",
        "id": "5K4W6rqBFWDnAN6FQUkS6x",
        "name": "Kanye West",
        "type": "artist",
        "uri": "spotify:artist:5K4W6rqBFWDnAN6FQUkS6x"
      },
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/20qISvAhX20dpIbOOzGK3q"
        },
        "href": "https://api.spotify.com/v1/artists/20qISvAhX20dpIbOOzGK3q",
        "id": "20qISvAhX20dpIbOOzGK3q",
        "name": "Nas",
        "type": "artist",
        "uri": "spotify:artist:20qISvAhX20dpIbOOzGK3q"
      },
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/69m0yjx8ruKebsRvbNuEDz"
        },
        "href": "https://api.spotify.com/v1/artists/69m0yjx8ruKebsRvbNuEDz",
        "id": "69m0yjx8ruKebsRvbNuEDz",
        "name": "Really Doe",
        "type": "artist",
        "uri": "spotify:artist:69m0yjx8ruKebsRvbNuEDz"
      }
    ],
    "available_markets": [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    "disc_number": 1,
    "duration_ms": 448000,
    "explicit": true,
    "external_ids": {
      "isrc": "USUM70502548"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/46fk9wjYcPm0sgym2b7EEE"
    },
    "href": "https://api.spotify.com/v1/tracks/46fk9wjYcPm0sgym2b7EEE",
    "id": "46fk9wjYcPm0sgym2b7EEE",
    "is_local": false,
    "name": "We Major",
    "popularity": 62,
    "preview_url": "https://p.scdn.co/mp3-preview/39230520170e190b84bd6761f02d4504dbb9cfc8?cid=cfe923b2d660439caf2b557b21f31221",
    "track_number": 14,
    "type": "track",
    "uri": "spotify:track:46fk9wjYcPm0sgym2b7EEE"
  };

  const obj3 = {
    "album": {
      "album_group": "album",
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/4hFBhdNVZZuVk5FYThUwaN"
          },
          "href": "https://api.spotify.com/v1/artists/4hFBhdNVZZuVk5FYThUwaN",
          "id": "4hFBhdNVZZuVk5FYThUwaN",
          "name": "アトラスサウンドチーム",
          "type": "artist",
          "uri": "spotify:artist:4hFBhdNVZZuVk5FYThUwaN"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JM",
        "JO",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/4pJT0WKggr4xk149X8A6KC"
      },
      "href": "https://api.spotify.com/v1/albums/4pJT0WKggr4xk149X8A6KC",
      "id": "4pJT0WKggr4xk149X8A6KC",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/ab67616d0000b2732a061f8cc383443cbb46adf6",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/ab67616d00001e022a061f8cc383443cbb46adf6",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/ab67616d000048512a061f8cc383443cbb46adf6",
          "width": 64
        }
      ],
      "name": "PERSONA5 ORIGINAL SOUNDTRACK",
      "release_date": "2017-01-17",
      "release_date_precision": "day",
      "total_tracks": 110,
      "type": "album",
      "uri": "spotify:album:4pJT0WKggr4xk149X8A6KC"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/5qEtLvXzYdv0G7c7rR6irX"
        },
        "href": "https://api.spotify.com/v1/artists/5qEtLvXzYdv0G7c7rR6irX",
        "id": "5qEtLvXzYdv0G7c7rR6irX",
        "name": "Lyn",
        "type": "artist",
        "uri": "spotify:artist:5qEtLvXzYdv0G7c7rR6irX"
      }
    ],
    "available_markets": [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    "disc_number": 1,
    "duration_ms": 277880,
    "explicit": false,
    "external_ids": {
      "isrc": "JPK651601422"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/5XLXrm5JVMdOus1fWmTOFw"
    },
    "href": "https://api.spotify.com/v1/tracks/5XLXrm5JVMdOus1fWmTOFw",
    "id": "5XLXrm5JVMdOus1fWmTOFw",
    "is_local": false,
    "name": "Beneath the Mask",
    "popularity": 62,
    "preview_url": "https://p.scdn.co/mp3-preview/7c8a601ee44879b74ae788681f21acea29b724e1?cid=cfe923b2d660439caf2b557b21f31221",
    "track_number": 29,
    "type": "track",
    "uri": "spotify:track:5XLXrm5JVMdOus1fWmTOFw"
  };

  const obj4 = {
    "album": {
      "album_group": "album",
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/2h93pZq0e7k5yf4dywlkpM"
          },
          "href": "https://api.spotify.com/v1/artists/2h93pZq0e7k5yf4dywlkpM",
          "id": "2h93pZq0e7k5yf4dywlkpM",
          "name": "Frank Ocean",
          "type": "artist",
          "uri": "spotify:artist:2h93pZq0e7k5yf4dywlkpM"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/3mH6qwIy9crq0I9YQbOuDf"
      },
      "href": "https://api.spotify.com/v1/albums/3mH6qwIy9crq0I9YQbOuDf",
      "id": "3mH6qwIy9crq0I9YQbOuDf",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/ab67616d0000b273c5649add07ed3720be9d5526",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/ab67616d00001e02c5649add07ed3720be9d5526",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/ab67616d00004851c5649add07ed3720be9d5526",
          "width": 64
        }
      ],
      "name": "Blonde",
      "release_date": "2016-08-20",
      "release_date_precision": "day",
      "total_tracks": 17,
      "type": "album",
      "uri": "spotify:album:3mH6qwIy9crq0I9YQbOuDf"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/2h93pZq0e7k5yf4dywlkpM"
        },
        "href": "https://api.spotify.com/v1/artists/2h93pZq0e7k5yf4dywlkpM",
        "id": "2h93pZq0e7k5yf4dywlkpM",
        "name": "Frank Ocean",
        "type": "artist",
        "uri": "spotify:artist:2h93pZq0e7k5yf4dywlkpM"
      }
    ],
    "available_markets": [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    "disc_number": 1,
    "duration_ms": 307151,
    "explicit": true,
    "external_ids": {
      "isrc": "QZ5C81600009"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/7eqoqGkKwgOaWNNHx90uEZ"
    },
    "href": "https://api.spotify.com/v1/tracks/7eqoqGkKwgOaWNNHx90uEZ",
    "id": "7eqoqGkKwgOaWNNHx90uEZ",
    "is_local": false,
    "name": "Nights",
    "popularity": 81,
    "preview_url": "https://p.scdn.co/mp3-preview/478a51ff059dc1abb20548ac2f3d3d73d75c3cb7?cid=cfe923b2d660439caf2b557b21f31221",
    "track_number": 9,
    "type": "track",
    "uri": "spotify:track:7eqoqGkKwgOaWNNHx90uEZ"
  };

  const obj5 = {
    "album": {
      "album_group": "album",
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/1Xyo4u8uXC1ZmMpatF05PJ"
          },
          "href": "https://api.spotify.com/v1/artists/1Xyo4u8uXC1ZmMpatF05PJ",
          "id": "1Xyo4u8uXC1ZmMpatF05PJ",
          "name": "The Weeknd",
          "type": "artist",
          "uri": "spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/3hhDpPtCFuQbppwYgsVhMO"
      },
      "href": "https://api.spotify.com/v1/albums/3hhDpPtCFuQbppwYgsVhMO",
      "id": "3hhDpPtCFuQbppwYgsVhMO",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/ab67616d0000b273e4860d5331509e2c9ee4de10",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/ab67616d00001e02e4860d5331509e2c9ee4de10",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/ab67616d00004851e4860d5331509e2c9ee4de10",
          "width": 64
        }
      ],
      "name": "Kiss Land",
      "release_date": "2013-09-10",
      "release_date_precision": "day",
      "total_tracks": 10,
      "type": "album",
      "uri": "spotify:album:3hhDpPtCFuQbppwYgsVhMO"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/1Xyo4u8uXC1ZmMpatF05PJ"
        },
        "href": "https://api.spotify.com/v1/artists/1Xyo4u8uXC1ZmMpatF05PJ",
        "id": "1Xyo4u8uXC1ZmMpatF05PJ",
        "name": "The Weeknd",
        "type": "artist",
        "uri": "spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ"
      }
    ],
    "available_markets": [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "IN",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "RW",
      "TG",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    "disc_number": 1,
    "duration_ms": 455333,
    "explicit": true,
    "external_ids": {
      "isrc": "USUM71310346"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/5idmfDT06TjCQ1SPDsa5qh"
    },
    "href": "https://api.spotify.com/v1/tracks/5idmfDT06TjCQ1SPDsa5qh",
    "id": "5idmfDT06TjCQ1SPDsa5qh",
    "is_local": false,
    "name": "Kiss Land",
    "popularity": 63,
    "preview_url": "https://p.scdn.co/mp3-preview/358854eee1f1a6abff073ace04ae44a5c77ef705?cid=cfe923b2d660439caf2b557b21f31221",
    "track_number": 8,
    "type": "track",
    "uri": "spotify:track:5idmfDT06TjCQ1SPDsa5qh"
  };

  const obj6 = {
    "album": {
      "album_group": "album",
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6liAMWkVf5LH7YR9yfFy1Y"
          },
          "href": "https://api.spotify.com/v1/artists/6liAMWkVf5LH7YR9yfFy1Y",
          "id": "6liAMWkVf5LH7YR9yfFy1Y",
          "name": "Portishead",
          "type": "artist",
          "uri": "spotify:artist:6liAMWkVf5LH7YR9yfFy1Y"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/3539EbNgIdEDGBKkUf4wno"
      },
      "href": "https://api.spotify.com/v1/albums/3539EbNgIdEDGBKkUf4wno",
      "id": "3539EbNgIdEDGBKkUf4wno",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/ab67616d0000b273dc20397b139223620af148f6",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/ab67616d00001e02dc20397b139223620af148f6",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/ab67616d00004851dc20397b139223620af148f6",
          "width": 64
        }
      ],
      "name": "Dummy",
      "release_date": "1994-01-01",
      "release_date_precision": "day",
      "total_tracks": 11,
      "type": "album",
      "uri": "spotify:album:3539EbNgIdEDGBKkUf4wno"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/6liAMWkVf5LH7YR9yfFy1Y"
        },
        "href": "https://api.spotify.com/v1/artists/6liAMWkVf5LH7YR9yfFy1Y",
        "id": "6liAMWkVf5LH7YR9yfFy1Y",
        "name": "Portishead",
        "type": "artist",
        "uri": "spotify:artist:6liAMWkVf5LH7YR9yfFy1Y"
      }
    ],
    "available_markets": [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    "disc_number": 1,
    "duration_ms": 302600,
    "explicit": false,
    "external_ids": {
      "isrc": "GBAQT9400065"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/6dDcfbMUFkFDk6x93kITY7"
    },
    "href": "https://api.spotify.com/v1/tracks/6dDcfbMUFkFDk6x93kITY7",
    "id": "6dDcfbMUFkFDk6x93kITY7",
    "is_local": false,
    "name": "Biscuit",
    "popularity": 48,
    "preview_url": "https://p.scdn.co/mp3-preview/7671c20ad3fe311a67a2ac169ffec1860fed838e?cid=cfe923b2d660439caf2b557b21f31221",
    "track_number": 10,
    "type": "track",
    "uri": "spotify:track:6dDcfbMUFkFDk6x93kITY7"
  };

  const obj7 = {
    "album": {
      "album_group": "album",
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/7w29UYBi0qsHi5RTcv3lmA"
          },
          "href": "https://api.spotify.com/v1/artists/7w29UYBi0qsHi5RTcv3lmA",
          "id": "7w29UYBi0qsHi5RTcv3lmA",
          "name": "Björk",
          "type": "artist",
          "uri": "spotify:artist:7w29UYBi0qsHi5RTcv3lmA"
        }
      ],
      "available_markets": [
        "CA",
        "US"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/5vBpIxm8ws6pWyVmTWiGE1"
      },
      "href": "https://api.spotify.com/v1/albums/5vBpIxm8ws6pWyVmTWiGE1",
      "id": "5vBpIxm8ws6pWyVmTWiGE1",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/ab67616d0000b273bc31229deb79f896eb9fee84",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/ab67616d00001e02bc31229deb79f896eb9fee84",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/ab67616d00004851bc31229deb79f896eb9fee84",
          "width": 64
        }
      ],
      "name": "Vespertine",
      "release_date": "2001",
      "release_date_precision": "year",
      "total_tracks": 12,
      "type": "album",
      "uri": "spotify:album:5vBpIxm8ws6pWyVmTWiGE1"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/7w29UYBi0qsHi5RTcv3lmA"
        },
        "href": "https://api.spotify.com/v1/artists/7w29UYBi0qsHi5RTcv3lmA",
        "id": "7w29UYBi0qsHi5RTcv3lmA",
        "name": "Björk",
        "type": "artist",
        "uri": "spotify:artist:7w29UYBi0qsHi5RTcv3lmA"
      }
    ],
    "available_markets": [
      "CA",
      "US"
    ],
    "disc_number": 1,
    "duration_ms": 338466,
    "explicit": false,
    "external_ids": {
      "isrc": "USEE10100733"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/5eacHz9AJcozOn3KuqzPQz"
    },
    "href": "https://api.spotify.com/v1/tracks/5eacHz9AJcozOn3KuqzPQz",
    "id": "5eacHz9AJcozOn3KuqzPQz",
    "is_local": false,
    "name": "Undo",
    "popularity": 40,
    "preview_url": "https://p.scdn.co/mp3-preview/9a840d230f41ad269f1de10f511bf7952064652e?cid=cfe923b2d660439caf2b557b21f31221",
    "track_number": 4,
    "type": "track",
    "uri": "spotify:track:5eacHz9AJcozOn3KuqzPQz"
  };

  const obj8 = {
    "album": {
      "album_group": "album",
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6yJ6QQ3Y5l0s0tn7b0arrO"
          },
          "href": "https://api.spotify.com/v1/artists/6yJ6QQ3Y5l0s0tn7b0arrO",
          "id": "6yJ6QQ3Y5l0s0tn7b0arrO",
          "name": "JPEGMAFIA",
          "type": "artist",
          "uri": "spotify:artist:6yJ6QQ3Y5l0s0tn7b0arrO"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/4inXqcdjG79gV4m2mU8dQh"
      },
      "href": "https://api.spotify.com/v1/albums/4inXqcdjG79gV4m2mU8dQh",
      "id": "4inXqcdjG79gV4m2mU8dQh",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/ab67616d0000b2736e57be9031cc8bc46fb17fee",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/ab67616d00001e026e57be9031cc8bc46fb17fee",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/ab67616d000048516e57be9031cc8bc46fb17fee",
          "width": 64
        }
      ],
      "name": "LP!",
      "release_date": "2021-10-22",
      "release_date_precision": "day",
      "total_tracks": 18,
      "type": "album",
      "uri": "spotify:album:4inXqcdjG79gV4m2mU8dQh"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/6yJ6QQ3Y5l0s0tn7b0arrO"
        },
        "href": "https://api.spotify.com/v1/artists/6yJ6QQ3Y5l0s0tn7b0arrO",
        "id": "6yJ6QQ3Y5l0s0tn7b0arrO",
        "name": "JPEGMAFIA",
        "type": "artist",
        "uri": "spotify:artist:6yJ6QQ3Y5l0s0tn7b0arrO"
      }
    ],
    "available_markets": [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    "disc_number": 1,
    "duration_ms": 324776,
    "explicit": true,
    "external_ids": {
      "isrc": "USUM72119677"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/2SRLd3XhmyP2wwQKVRDDy4"
    },
    "href": "https://api.spotify.com/v1/tracks/2SRLd3XhmyP2wwQKVRDDy4",
    "id": "2SRLd3XhmyP2wwQKVRDDy4",
    "is_local": false,
    "name": "SICK, NERVOUS & BROKE!",
    "popularity": 50,
    "preview_url": "https://p.scdn.co/mp3-preview/428b4936bad3e5ab8b11339d24990a300bccfccb?cid=cfe923b2d660439caf2b557b21f31221",
    "track_number": 11,
    "type": "track",
    "uri": "spotify:track:2SRLd3XhmyP2wwQKVRDDy4"
  };

function App() {
    return (
        <>
            <Bracket players={[obj,obj2,obj3,obj4,obj5,obj6,obj7,obj8]}/>
        </>
    );
}

export default App;
